theme = "solarized_light"
# theme = "solarized_dark"

# Should be able to do this when the next update comes out.
# [theme]
# dark = "solarized_dark"
# light = "solarized_light"

[editor]
# Use system clipboard.
default-yank-register = "+"

[editor.file-picker]
hidden = false

[keys.normal]
# Using C-c feels weird.
"#" = "toggle_comments"
