[[language]]
name = "markdown"
formatter = { command = 'prettier' }

[[language]]
name = "javascript"
formatter = { command = 'prettier' }

[[language]]
name = "typescript"
formatter = { command = 'prettier' }

[[language]]
name = "tsx"
formatter = { command = 'prettier' }

[[language]]
name = "lua"
formatter = { command = "stylua", args = [ "-" ] }

[[language]]
name = "yaml"
formatter = { command = 'prettier' }

[[language]]
name = "python"
formatter = { command = "ruff", args = ["format", "-"] }
